### ISSUE TITLE
computer interaction

### ISSUE THREAD

**Issue by lukeplechaty** [BiggerSeries/BiggerReactors#12]
computers can't read the battery funtion as it only give out nil as of 0.5.0-beta

**Comment by RogueLogix** [comment]
Fixed in 0.5.0-beta.1
https://github.com/BiggerSeries/BiggerReactors/commit/6daa79dcc51fea94d8946abce45ccfdd63deb3c7

**Comment by lukeplechaty** [comment]
that the ver i got and it still not fixed


[12:24:32] [ComputerCraft-Coroutine-1/WARN]: Received unknown type 'net.roguelogix.biggerreactors.multiblocks.reactor.deps.ReactorPeripheral$Battery', returning nil.
[12:24:41] [ComputerCraft-Coroutine-1/WARN]: Received unknown type 'net.roguelogix.biggerreactors.multiblocks.reactor.deps.ReactorPeripheral$Battery', returning nil.
[12:25:04] [ComputerCraft-Coroutine-1/WARN]: Received unknown type 'net.roguelogix.biggerreactors.multiblocks.reactor.deps.ReactorPeripheral$Battery', returning nil.
[12:27:15] [ComputerCraft-Coroutine-1/WARN]: Lua Method net.roguelogix.biggerreactors.multiblocks.reactor.deps.ReactorPeripheral$FuelTank.capacity should be final.
[12:27:15] [ComputerCraft-Coroutine-1/WARN]: Lua Method net.roguelogix.biggerreactors.multiblocks.reactor.deps.ReactorPeripheral$FuelTank.fuel should be final.
[12:27:15] [ComputerCraft-Coroutine-1/WARN]: Lua Method net.roguelogix.biggerreactors.multiblocks.reactor.deps.ReactorPeripheral$FuelTank.ejectWaste should be final.
[12:27:15] [ComputerCraft-Coroutine-1/WARN]: Lua Method net.roguelogix.biggerreactors.multiblocks.reactor.deps.ReactorPeripheral$FuelTank.waste should be final.
[12:27:15] [ComputerCraft-Coroutine-1/WARN]: Lua Method net.roguelogix.biggerreactors.multiblocks.reactor.deps.ReactorPeripheral$FuelTank.totalReactant should be final.
[12:27:15] [ComputerCraft-Coroutine-1/WARN]: Lua Method net.roguelogix.biggerreactors.multiblocks.reactor.deps.ReactorPeripheral$FuelTank.burnedLastTick should be final.
[12:27:15] [ComputerCraft-Coroutine-1/WARN]: Lua Method net.roguelogix.biggerreactors.multiblocks.reactor.deps.ReactorPeripheral$FuelTank.fuelReactivity should be final.

**Comment by RogueLogix** [comment]
thats the exact issue i fixed in that commit, so, you aren't on beta.1
